apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-events-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-events-processor
  template:
    metadata:
      labels:
        app: todo-events-processor
    spec:
      serviceAccountName: todoa-app-sa
      containers:
      - name: todo-events-processor
        image: farfocel.azurecr.io/todo/todo-events-processor:latest
        resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256'
              memory: 11400G