apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: todo-app
          image: farfocel.azurecr.io/todo-app:latest
          env:
          - name: ConnectionStrings__DefaultConnection
            value: 'Server=vsoft00.database.windows.net;Authentication=Active Directory Default;Database=vsoftsql;MultipleActiveResultSets=True'
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256'
              memory: 11400G