name: Docker Image CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: ACR build
      id: build-push-acr
      uses: azure/acr-build@v1
      with:
        service_principal: ${{ secrets.AZURE_CLIENT_ID }}
        service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant: ${{ secrets.AZURE_TENANT_ID }}
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        repository: todo
        image:  todo-app
        folder: src/ToDo
        branch: main
        tag: ${{ github.sha }}

    - name: Check
      run: docker image ls
      
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ secrets.resource_group }}' 
        cluster-name: '${{ secrets.cluster_name }}'
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to AKS
      id: deploy-aks
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'default'
        manifests: |
           deployment.yaml
           service.yaml
           ingress.yaml
        images: '${{ secrets.registry }}.azurecr.io/todo-app:${{ github.sha }}'
        pull-images: false 
